# Display Name of the workflow
name: Static Analysis - Advanced Secret Scan

# When this workflow triggers
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Allow this workflow to be called from another workflow
    workflow_call:

    # Run the unit tests on every change
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

# Define each session of execution that should be executed
jobs:
  SecretScan:
    # Display name of the job
    name: Scan for Secrets

    # Operating system filter for the runners
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Clone Repo
        uses: actions/checkout@v5

      - name: Scan for Secrets  
        uses: trufflesecurity/trufflehog@main
