# Display Name of the workflow
name: Static Analysis - Lint

# When this workflow triggers
on:
    # Allows this workflow to be manually run
    workflow_dispatch:

    # Allow this workflow to be called from another workflow
    workflow_call:

    # Run the linting checks on every change
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Define each session of execution that should be executed
jobs:
    Lint:
        # Display name of the job
        name: Lint

        # Operating system filter for the runners
        runs-on: ubuntu-slim

        # Set explicit least permission
        permissions:
            contents: read

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v7
              background: true

            # Set up NodeJS on the build host
            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              background: true
              with:
                  node-version: 24

            # Set up the socket firewall binary
            - name: Install - Socket Firewall
              uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f
              background: true
              with:
                  mode: firewall-free

            # Bring job back to sync execution by awaiting for all async jobs to finish before continuing
            - name: Steps - Convert Back To Synchronous Execution - Setup
              wait-all: true

            # Update the NPM client to the latest version
            - name: Update NPM Client
              run: sfw npm install -g npm

            # Install all of the dependencies
            - name: Install All of the Project Dependencies
              run: sfw npm ci

            # Lint the Source code to ensure project standardization and best practices
            - name: Lint Source Code
              run: npm run lint
